version: "3.8"

services:
  nginx:
    image: jc002/nginx
    container_name: nginx-devops
    ports:
      - "80:80"
    links:
      - devops
    networks:
      devops-network:
        ipv4_address: 172.11.0.3
  devops:
    container_name: devops
    image: jc002/devops
    ports:
      - "9000:9000"
    networks:
      devops-network:
        ipv4_address: 172.11.0.7
  mysql:
    image: mariadb:10.6.10
    container_name: devops-db
    restart: "on-failure"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"
    volumes:
      - devops-db:/var/lib/mysql
    networks:
      devops-network:
        ipv4_address: 172.11.0.2
networks:
  devops-network:
    name: devops-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/16
volumes:
  devops-db:
    external: true
